### PR TITLE
Improve plugin logo and file icon

### PR DESCRIPTION
**Pull request by tim-sh**

### CODE REVIEW

**Comment by tim-sh** [comment]
Tested to work.

**Review by chgeo — APPROVED** [review]
Rene informed me about this

**Comment by tim-sh** [comment]
The two logos are very different in size and they seem vertically aligned at the bottom:

grafik

That look ok?

**Comment by chgeo** [comment]
That looks ok.  We don't need to be artistic here.

**Review by renejeglinsky — APPROVED** [review]

**Pull request merged**
